name: deeppricing
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - _tflow_select=2.3.0=mkl
  - abseil-cpp=20211102.0=hd4dd3e8_0
  - absl-py=2.1.0=py310h06a4308_0
  - aiodns=3.5.0=py310h06a4308_1
  - aiohappyeyeballs=2.6.1=py310h06a4308_0
  - aiohttp=3.13.2=py310hee96239_0
  - aiosignal=1.4.0=py310h06a4308_0
  - anyio=4.10.0=py310h06a4308_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py310hee96239_0
  - astroid=4.0.2=py310h06a4308_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - astunparse=1.6.3=py_0
  - async-lru=2.0.5=py310h06a4308_0
  - async-timeout=5.0.1=py310h06a4308_0
  - attrs=25.4.0=py310h06a4308_2
  - babel=2.17.0=py310h06a4308_0
  - beautifulsoup4=4.14.2=py310h06a4308_0
  - blas=1.0=mkl
  - bleach=6.3.0=py310h06a4308_0
  - bottleneck=1.4.2=py310haa0f9ac_1
  - brotlicffi=1.1.0.0=py310hbdd6827_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cachetools=5.5.1=py310h06a4308_0
  - certifi=2025.11.12=py310h06a4308_0
  - cffi=2.0.0=py310h4eded50_1
  - charset-normalizer=3.4.4=py310h06a4308_0
  - click=8.2.1=py310h06a4308_1
  - comm=0.2.3=py310h06a4308_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cryptography=46.0.2=py310h498d7c9_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h9c0eb46_1
  - dbus=1.16.2=h5bd4931_0
  - debugpy=1.8.16=py310hbdd6827_1
  - decorator=5.2.1=py310h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.4.0=py310h06a4308_0
  - exceptiongroup=1.3.0=py310h06a4308_0
  - executing=2.2.1=py310h06a4308_0
  - expat=2.7.3=h3385a95_0
  - flatbuffers=25.2.10=h6a678d5_0
  - fontconfig=2.14.1=h4c34cd2_2
  - fonttools=4.60.1=py310hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - frozenlist=1.8.0=py310hbdd6827_0
  - gast=0.4.0=pyhd3eb1b0_0
  - giflib=5.2.2=h5eee18b_0
  - glib=2.84.4=h5bdd934_0
  - glib-tools=2.84.4=h8875d55_0
  - google-auth=2.38.0=py310h06a4308_1
  - google-auth-oauthlib=0.5.2=py310h06a4308_0
  - google-pasta=0.2.0=pyhd3eb1b0_0
  - grpc-cpp=1.48.2=h5bf31a4_0
  - grpcio=1.48.2=py310h5bf31a4_0
  - gst-plugins-base=1.14.1=h6a678d5_1
  - gstreamer=1.14.1=h5eee18b_1
  - h11=0.16.0=py310h06a4308_1
  - h5py=3.12.1=py310hc0802c4_0
  - hdf5=1.12.1=h70be1eb_2
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py310h06a4308_0
  - httpx=0.28.1=py310h06a4308_1
  - icu=58.2=he6710b0_3
  - idna=3.11=py310h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - ipykernel=6.31.0=py310h7040dfc_0
  - ipython=8.30.0=py310h06a4308_0
  - isort=6.1.0=py310h06a4308_0
  - jedi=0.19.2=py310h06a4308_0
  - jinja2=3.1.6=py310h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.12.1=py310h06a4308_0
  - jsonschema=4.25.0=py310h06a4308_1
  - jsonschema-specifications=2025.9.1=py310h06a4308_0
  - jupyter-lsp=2.2.5=py310h06a4308_0
  - jupyter_client=8.6.3=py310h06a4308_1
  - jupyter_core=5.9.1=py310h06a4308_0
  - jupyter_events=0.12.0=py310h06a4308_0
  - jupyter_server=2.16.0=py310h06a4308_0
  - jupyter_server_terminals=0.5.3=py310h06a4308_0
  - jupyterlab=4.5.0=py310h06a4308_0
  - jupyterlab_pygments=0.3.0=py310h06a4308_0
  - jupyterlab_server=2.28.0=py310h06a4308_0
  - keras=2.12.0=py310h06a4308_0
  - keras-preprocessing=1.1.2=pyhd3eb1b0_0
  - kiwisolver=1.4.9=py310h24d9097_0
  - krb5=1.20.1=h568e23c_1
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libclang=14.0.6=default_hc6dbbc7_2
  - libclang13=14.0.6=default_he11475f_2
  - libcups=2.4.2=ha637b67_0
  - libcurl=8.2.1=h91b91d3_0
  - libdeflate=1.22=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libiconv=1.16=h5eee18b_3
  - libllvm14=14.0.6=hecde1de_4
  - libnghttp2=1.52.0=ha637b67_1
  - libnsl=2.0.0=h5eee18b_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpng=1.6.50=h2ed474d_0
  - libpq=12.15=h37d81fd_1
  - libprotobuf=3.20.3=he621ea3_0
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.10.0=h37d81fd_2
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libtiff=4.7.1=h029b1ac_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.0.1=h5eee18b_1
  - libxml2=2.10.4=hcbfbd50_0
  - libzlib=1.3.1=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown=3.8=py310h06a4308_0
  - markupsafe=3.0.2=py310h5eee18b_0
  - matplotlib=3.10.6=py310h06a4308_1
  - matplotlib-base=3.10.6=py310h71dd3da_1
  - matplotlib-inline=0.2.1=py310h06a4308_0
  - mccabe=0.7.0=pyhd3eb1b0_0
  - mistune=3.1.2=py310h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py310h5eee18b_2
  - mkl_fft=1.3.11=py310h5eee18b_0
  - mkl_random=1.2.8=py310h1128e8f_0
  - multidict=6.7.0=py310hee96239_0
  - mysql=5.7.24=he378463_2
  - nbclient=0.10.2=py310h06a4308_0
  - nbconvert-core=7.16.6=py310h06a4308_0
  - nbformat=5.10.4=py310h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py310h06a4308_0
  - notebook=7.5.0=py310h06a4308_0
  - notebook-shim=0.2.4=py310h06a4308_0
  - numexpr=2.11.0=py310hf4471f9_0
  - numpy=1.23.5=py310h5f9d8c6_1
  - numpy-base=1.23.5=py310hb5e798b_1
  - oauthlib=3.3.1=py310h06a4308_0
  - openjpeg=2.5.4=h4e0627c_1
  - openssl=1.1.1w=h7f8727e_0
  - opt_einsum=3.3.0=pyhd3eb1b0_1
  - overrides=7.7.0=py310h06a4308_0
  - packaging=25.0=py310h06a4308_1
  - pandas=2.3.3=py310h23c847b_1
  - pandas-stubs=2.3.2.250926=py310h06a4308_0
  - pandocfilters=1.5.1=py310h06a4308_0
  - parso=0.8.5=py310h06a4308_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py310h06a4308_1
  - pillow=11.1.0=py310hac6e08b_1
  - platformdirs=4.5.0=py310h06a4308_0
  - prometheus_client=0.21.1=py310h06a4308_0
  - prompt-toolkit=3.0.52=py310h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.3.1=py310h5eee18b_0
  - protobuf=3.20.3=py310h6a678d5_0
  - psutil=7.0.0=py310hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py310h06a4308_0
  - pyasn1=0.6.1=py310h06a4308_0
  - pyasn1-modules=0.4.2=py310h06a4308_0
  - pycares=4.10.0=py310ha137689_0
  - pycparser=2.23=py310h06a4308_0
  - pygments=2.19.2=py310h06a4308_0
  - pylint=4.0.3=py310h06a4308_0
  - pyopenssl=25.3.0=py310hef88997_0
  - pyparsing=3.2.5=py310h06a4308_0
  - pyqt=5.15.11=py310h144e999_0
  - pyqt5-sip=12.17.0=py310hee96239_0
  - pysocks=1.7.1=py310h06a4308_1
  - python=3.10.13=h7a1cb2a_0
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python-fastjsonschema=2.21.2=py310h06a4308_0
  - python-flatbuffers=24.3.25=py310h06a4308_0
  - python-json-logger=4.0.0=py310h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py310h06a4308_0
  - pyyaml=6.0.3=py310h591646f_0
  - pyzmq=27.1.0=py310hcf8288c_1
  - qt-main=5.15.2=h5b8104b_9
  - re2=2022.04.01=h295c915_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py310h06a4308_0
  - requests=2.32.5=py310h06a4308_1
  - requests-oauthlib=2.0.0=py310h06a4308_0
  - rfc3339-validator=0.1.4=py310h06a4308_0
  - rfc3986-validator=0.1.1=py310h06a4308_0
  - rpds-py=0.28.0=py310h498d7c9_0
  - rsa=4.7.2=pyhd3eb1b0_1
  - scipy=1.15.3=py310h525edd1_0
  - seaborn=0.13.2=py310h06a4308_3
  - send2trash=1.8.2=py310h06a4308_1
  - sip=6.12.0=py310h7934f7d_0
  - six=1.17.0=py310h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.1=py310h06a4308_0
  - soupsieve=2.5=py310h06a4308_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboard=2.12.1=py310h06a4308_0
  - tensorboard-data-server=0.7.0=py310h52d8a92_1
  - tensorboard-plugin-wit=1.8.1=py310h06a4308_0
  - tensorflow=2.12.0=mkl_py310hc7ea715_0
  - tensorflow-base=2.12.0=mkl_py310he5f8e37_0
  - tensorflow-estimator=2.12.0=py310h06a4308_0
  - termcolor=3.2.0=py310h06a4308_0
  - terminado=0.18.1=py310h06a4308_0
  - tinycss2=1.4.0=py310h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py310h06a4308_0
  - tomlkit=0.13.3=py310h06a4308_0
  - tornado=6.5.1=py310h5eee18b_0
  - traitlets=5.14.3=py310h06a4308_0
  - typing-extensions=4.15.0=py310h06a4308_0
  - typing_extensions=4.15.0=py310h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.5.0=py310h06a4308_0
  - uvloop=0.22.1=py310h939ff40_1
  - wcwidth=0.2.13=py310h06a4308_0
  - webencodings=0.5.1=py310h06a4308_1
  - websocket-client=1.8.0=py310h06a4308_0
  - werkzeug=3.1.3=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - wrapt=2.0.1=py310h47b2149_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py310hee96239_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - pip==24.3.1
      - setuptools==44.1.1
